title:            "Elina"
description:      "a student"
url:              "http://tinysun1993.github.io"
signoff:          "tinysun"
disqus_shortname: "mednoter"
facebook_appid:   "407484809306168"
google_analytics: ""
timezone:         Asia/Beijing
highlighter:      pygments
future:           true
repository_url:   https://github.com/tinysun1993/tinysun1993.github.io

links:
  - name:         Blog
    url:          /
  - name:         Friends
    url:          /links.html
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about.html

permalink:        /:title.html
markdown:         kramdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
sass:
  style: compressed
